version: "3"

services:
  app:
    image: ruby:2.7.2
    links:
      - mysql
      - redis
    ports:
      - "3000:3000"
    build: .
    environment:
      RAILS_ENV: $RAILS_ENV

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "${LONGBRIDGE_REDIS_PORT:-6379}:6379"

volumes:
  mysql:
